// registry/radiant-lines/radiant-lines.svelte
<script module>
</script>

<script>
  import { onMount } from "svelte"

  import { cn } from "$lib/utils"
  import {
    createRadiantLines,
    DEFAULT_COLORS,
    type RadiantLinesInstance,
    type RadiantLinesOptions,
  } from "./radiant-lines-vanilla"

  interface Props extends Omit<RadiantLinesOptions, "container"> {
    class?: string
    container?: HTMLElement
  }

  let {
    class: className = "",
    colors = DEFAULT_COLORS,
    starCount = 420,
    container,
  }: Props = $props()

  let canvas: HTMLCanvasElement | undefined = $state()
  let instance: RadiantLinesInstance | null = null

  onMount(() => {
    if (!canvas) return
    instance = createRadiantLines(canvas, {
      colors,
      starCount,
      container: container ?? null,
    })
    return () => {
      instance?.destroy()
      instance = null
    }
  })

  $effect(() => {
    instance?.setOptions({
      colors,
      starCount,
      container: container ?? null,
    })
  })
</script>

<div
  data-slot="radiant-lines"
  aria-hidden="true"
  class={cn(
    "pointer-events-none absolute inset-0 overflow-hidden bg-background",
    className
  )}
>
  <canvas bind:this={canvas} class="absolute inset-0 size-full"></canvas>
</div>

// registry/radiant-lines/radiant-lines.tsx
"use client"

import { useEffect, useRef, type RefObject } from "react"

import { cn } from "@/lib/utils"

import {
  createRadiantLines,
  type RadiantLinesInstance,
  type RadiantLinesOptions,
} from "./radiant-lines-vanilla"

export { DEFAULT_COLORS } from "./radiant-lines-vanilla"
export type {
  RadiantLinesInstance,
  RadiantLinesOptions,
} from "./radiant-lines-vanilla"

export type RadiantLinesProps = Omit<RadiantLinesOptions, "container"> & {
  className?: string
  /**
   * Scroll container. Omit to use the window.
   * Pass a ref when the component lives inside an overflow scroller.
   */
  containerRef?: RefObject<HTMLElement | null>
}

/**
 * Hyperspace starfield — colored streaks radiate from the center.
 * Transparent canvas over `bg-background` (shadcn theme).
 */
export function RadiantLines({
  className,
  colors,
  starCount = 420,
  containerRef,
}: RadiantLinesProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const instanceRef = useRef<RadiantLinesInstance | null>(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    instanceRef.current = createRadiantLines(canvas, {
      colors,
      starCount,
      container: containerRef?.current ?? null,
    })
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
    // Engine reads live options via setOptions; mount once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    instanceRef.current?.setOptions({
      colors,
      starCount,
      container: containerRef?.current ?? null,
    })
  }, [colors, starCount, containerRef])

  return (
    <div
      data-slot="radiant-lines"
      aria-hidden
      className={cn(
        "pointer-events-none absolute inset-0 overflow-hidden bg-background",
        className
      )}
    >
      <canvas ref={canvasRef} className="absolute inset-0 size-full" />
    </div>
  )
}
