// registry/ring-tower/ring-tower.tsx
"use client"

import { useEffect, useRef } from "react"

import { cn } from "@/lib/utils"

import {
  createRingTower,
  DEFAULT_BACKFACE,
  DEFAULT_PARALLAX,
  DEFAULT_RINGS,
  DEFAULT_SPEED,
  type RingTowerInstance,
  type RingTowerOptions,
} from "./ring-tower-vanilla"

export {
  DEFAULT_BACKFACE,
  DEFAULT_PARALLAX,
  DEFAULT_RINGS,
  DEFAULT_SPEED,
} from "./ring-tower-vanilla"
export type {
  RingTowerInstance,
  RingTowerOptions,
  RingTowerTheme,
} from "./ring-tower-vanilla"

export type RingTowerProps = RingTowerOptions & {
  className?: string
}

/**
 * A tower of tilted bands wrapped in your images. The images crawl around
 * the bands, dragging spins the tower, and the pointer turns neighboring
 * bands opposite ways. Transparent; the parent paints the background.
 * Theme-aware.
 */
export function RingTower({
  className,
  images,
  rings = DEFAULT_RINGS,
  speed = DEFAULT_SPEED,
  draggable = true,
  parallax = DEFAULT_PARALLAX,
  backface = DEFAULT_BACKFACE,
  theme = "auto",
}: RingTowerProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const instanceRef = useRef<RingTowerInstance | null>(null)

  useEffect(() => {
    const root = rootRef.current
    if (!root) return
    instanceRef.current = createRingTower(root, {
      images,
      rings,
      speed,
      draggable,
      parallax,
      backface,
      theme,
    })
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
    // Engine reads live options via setOptions; mount once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    instanceRef.current?.setOptions({
      images,
      rings,
      speed,
      draggable,
      parallax,
      backface,
      theme,
    })
  }, [images, rings, speed, draggable, parallax, backface, theme])

  return (
    <div
      ref={rootRef}
      data-slot="ring-tower"
      aria-hidden
      className={cn(
        "absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]",
        className
      )}
    />
  )
}

// registry/ring-tower/ring-tower.svelte
<script module lang="ts">
</script>

<script lang="ts">
  import { onMount } from "svelte"
  import {
    createRingTower,
    DEFAULT_BACKFACE,
    DEFAULT_PARALLAX,
    DEFAULT_RINGS,
    DEFAULT_SPEED,
    type RingTowerInstance,
    type RingTowerOptions,
  } from "./ring-tower-vanilla"

  function cn(...parts: Array<string | false | null | undefined>) {
    return parts.filter(Boolean).join(" ")
  }

  interface Props extends RingTowerOptions {
    class?: string
  }

  let {
    class: className = "",
    images,
    rings = DEFAULT_RINGS,
    speed = DEFAULT_SPEED,
    draggable = true,
    parallax = DEFAULT_PARALLAX,
    backface = DEFAULT_BACKFACE,
    theme = "auto",
  }: Props = $props()

  let root: HTMLDivElement | undefined = $state()
  let instance: RingTowerInstance | null = null

  onMount(() => {
    if (!root) return
    instance = createRingTower(root, {
      images,
      rings,
      speed,
      draggable,
      parallax,
      backface,
      theme,
    })
    return () => {
      instance?.destroy()
      instance = null
    }
  })

  $effect(() => {
    instance?.setOptions({
      images,
      rings,
      speed,
      draggable,
      parallax,
      backface,
      theme,
    })
  })
</script>

<div
  bind:this={root}
  data-slot="ring-tower"
  aria-hidden="true"
  class={cn("absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]", className)}
></div>
