// registry/dithered-404/dithered-404.tsx
"use client"

import { useEffect, useRef, useState } from "react"

import { cn } from "@/lib/utils"

import {
  createDithered404,
  type Dithered404Instance,
  type Dithered404Options,
} from "./dithered-404-vanilla"

export { DARK_COLOR, LIGHT_COLOR } from "./dithered-404-vanilla"
export type {
  Dithered404Instance,
  Dithered404Options,
  Dithered404Theme,
} from "./dithered-404-vanilla"

export type Dithered404Props = Dithered404Options & {
  className?: string
}

/**
 * Bayer-pixel 404 section — a fireball cursor scorches and burns
 * the glyph into embers and smoke, then the type reforms.
 * `dither={false}` is a soft realistic fire.
 */
export function Dithered404({
  className,
  color,
  pixelSize = 4,
  brush = 28,
  interactive = true,
  dither = true,
  theme = "auto",
}: Dithered404Props) {
  const wrapRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const instanceRef = useRef<Dithered404Instance | null>(null)
  const [hideCursor, setHideCursor] = useState(false)

  useEffect(() => {
    const wrap = wrapRef.current
    const canvas = canvasRef.current
    if (!wrap || !canvas) return
    instanceRef.current = createDithered404(wrap, canvas, {
      color,
      pixelSize,
      brush,
      interactive,
      dither,
      theme,
      onHideCursor: setHideCursor,
    })
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
    // Engine reads live options via setOptions; mount once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    instanceRef.current?.setOptions({
      color,
      pixelSize,
      brush,
      interactive,
      dither,
      theme,
      onHideCursor: setHideCursor,
    })
  }, [color, pixelSize, brush, interactive, dither, theme])

  return (
    <div
      ref={wrapRef}
      data-slot="dithered-404"
      className={cn(
        "absolute inset-0 touch-none overflow-hidden",
        hideCursor && interactive && "cursor-none",
        className
      )}
    >
      <span className="sr-only">404</span>
      <canvas ref={canvasRef} className="absolute inset-0 size-full" />
    </div>
  )
}

// registry/dithered-404/dithered-404.svelte
<script module>
</script>

<script>
  import { onMount } from "svelte"

  import { cn } from "$lib/utils"
  import {
    createDithered404,
    type Dithered404Instance,
    type Dithered404Options,
  } from "./dithered-404-vanilla"

  interface Props extends Dithered404Options {
    class?: string
  }

  let {
    class: className = "",
    color,
    pixelSize = 4,
    brush = 28,
    interactive = true,
    dither = true,
    theme = "auto",
  }: Props = $props()

  let wrap: HTMLDivElement | undefined = $state()
  let canvas: HTMLCanvasElement | undefined = $state()
  let hideCursor = $state(false)
  let instance: Dithered404Instance | null = null

  onMount(() => {
    if (!wrap || !canvas) return
    instance = createDithered404(wrap, canvas, {
      color,
      pixelSize,
      brush,
      interactive,
      dither,
      theme,
      onHideCursor: (hide) => {
        hideCursor = hide
      },
    })
    return () => {
      instance?.destroy()
      instance = null
    }
  })

  $effect(() => {
    instance?.setOptions({
      color,
      pixelSize,
      brush,
      interactive,
      dither,
      theme,
    })
  })
</script>

<div
  bind:this={wrap}
  data-slot="dithered-404"
  class={cn(
    "absolute inset-0 touch-none overflow-hidden",
    hideCursor && interactive && "cursor-none",
    className
  )}
>
  <span class="sr-only">404</span>
  <canvas bind:this={canvas} class="absolute inset-0 size-full"></canvas>
</div>
