// registry/shader-sky/shader-sky.svelte
<script module lang="ts">
</script>

<script lang="ts">
  import { onMount } from "svelte"
  import {
    createShaderSky,
    skyFallback,
    resolveDark,
    type ShaderSkyInstance,
    type ShaderSkyOptions,
  } from "./shader-sky-vanilla"

  function cn(...parts: Array<string | false | null | undefined>) {
    return parts.filter(Boolean).join(" ")
  }

  interface Props extends Omit<ShaderSkyOptions, "onThemeChange"> {
    class?: string
  }

  let {
    class: className = "",
    colors,
    speed = 0.1,
    coverage = 0.5,
    intensity = 0.9,
    amount = 0.5,
    scale = 0.4,
    variation = 0.7,
    interactive = false,
    lightning = false,
    glass = false,
    glassSize = 7,
    theme = "auto",
  }: Props = $props()

  let canvas: HTMLCanvasElement | undefined = $state()
  let isDark = $state(false)
  let instance: ShaderSkyInstance | null = null

  onMount(() => {
    const sync = () => {
      isDark = resolveDark(theme)
    }
    sync()
    const mo = new MutationObserver(sync)
    mo.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "data-theme"],
    })
    const mq = window.matchMedia("(prefers-color-scheme: dark)")
    mq.addEventListener("change", sync)

    if (!canvas) {
      return () => {
        mo.disconnect()
        mq.removeEventListener("change", sync)
      }
    }
    instance = createShaderSky(canvas, {
      colors,
      speed,
      coverage,
      intensity,
      amount,
      scale,
      variation,
      interactive,
      lightning,
      glass,
      glassSize,
      theme,
      onThemeChange: (dark) => {
        isDark = dark
      },
    })
    return () => {
      mo.disconnect()
      mq.removeEventListener("change", sync)
      instance?.destroy()
      instance = null
    }
  })

  $effect(() => {
    isDark = resolveDark(theme)
  })

  $effect(() => {
    instance?.setOptions({
      colors,
      speed,
      coverage,
      intensity,
      amount,
      scale,
      variation,
      interactive,
      lightning,
      glass,
      glassSize,
      theme,
    })
  })

  const fallback = $derived(skyFallback(colors, isDark))
</script>

<div
  data-slot="shader-sky"
  aria-hidden="true"
  class={cn("pointer-events-none absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]", className)}
  style="background-color: {fallback.backgroundColor}; background-image: {fallback.backgroundImage};"
>
  <!-- Firefox can hand an opaque WebGL canvas straight to the system
       compositor, which ignores rounded clips. The mask on the root keeps it
       in the page's own layer, so the parent's radius holds. -->
  <canvas bind:this={canvas} class="absolute inset-0 size-full rounded-[inherit]"></canvas>
</div>

// registry/shader-sky/shader-sky.tsx
"use client"

import { useEffect, useRef, useState } from "react"

import { cn } from "@/lib/utils"

import {
  createShaderSky,
  skyFallback,
  resolveDark,
  type ShaderSkyInstance,
  type ShaderSkyOptions,
} from "./shader-sky-vanilla"

export {
  DARK_COLORS,
  DARK_FALLBACK,
  LIGHT_COLORS,
  LIGHT_FALLBACK,
} from "./shader-sky-vanilla"
export type {
  ShaderSkyInstance,
  ShaderSkyOptions,
  ShaderSkyTheme,
} from "./shader-sky-vanilla"

export type ShaderSkyProps = Omit<ShaderSkyOptions, "onThemeChange"> & {
  className?: string
}

/**
 * WebGL sky for heroes: clear blue with drifting clouds in light,
 * storm gray in dark, with optional lightning. Optional window-glass film.
 */
export function ShaderSky({
  className,
  colors,
  speed = 0.1,
  coverage = 0.5,
  intensity = 0.9,
  amount = 0.5,
  scale = 0.4,
  variation = 0.7,
  interactive = false,
  lightning = false,
  glass = false,
  glassSize = 7,
  theme = "auto",
}: ShaderSkyProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const instanceRef = useRef<ShaderSkyInstance | null>(null)
  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    const sync = () => setIsDark(resolveDark(theme))
    sync()
    const mo = new MutationObserver(sync)
    mo.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "data-theme"],
    })
    const mq = window.matchMedia("(prefers-color-scheme: dark)")
    mq.addEventListener("change", sync)
    return () => {
      mo.disconnect()
      mq.removeEventListener("change", sync)
    }
  }, [theme])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    instanceRef.current = createShaderSky(canvas, {
      colors,
      speed,
      coverage,
      intensity,
      amount,
      scale,
      variation,
      interactive,
      lightning,
      glass,
      glassSize,
      theme,
      onThemeChange: setIsDark,
    })
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
    // Engine reads live options via setOptions; mount once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    instanceRef.current?.setOptions({
      colors,
      speed,
      coverage,
      intensity,
      amount,
      scale,
      variation,
      interactive,
      lightning,
      glass,
      glassSize,
      theme,
      onThemeChange: setIsDark,
    })
  }, [
    colors,
    speed,
    coverage,
    intensity,
    amount,
    scale,
    variation,
    interactive,
    lightning,
    glass,
    glassSize,
    theme,
  ])

  const fallback = skyFallback(colors, isDark)

  return (
    <div
      data-slot="shader-sky"
      aria-hidden
      className={cn(
        "pointer-events-none absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]",
        className
      )}
      style={{
        backgroundColor: fallback.backgroundColor,
        backgroundImage: fallback.backgroundImage,
      }}
    >
      {/* Firefox can hand an opaque WebGL canvas straight to the system
          compositor, which ignores rounded clips. The mask on the root keeps
          it in the page's own layer, so the parent's radius holds. */}
      <canvas
        ref={canvasRef}
        className="absolute inset-0 size-full rounded-[inherit]"
      />
    </div>
  )
}
