// registry/shader-gradient/shader-gradient.svelte
<script module lang="ts">
</script>

<script lang="ts">
  import { onMount } from "svelte"
  import {
    createShaderGradient,
    DARK_FALLBACK,
    DEFAULT_BLUR,
    DEFAULT_GRAIN,
    DEFAULT_INTENSITY,
    DEFAULT_SPEED,
    LIGHT_FALLBACK,
    resolveDark,
    type ShaderGradientInstance,
    type ShaderGradientOptions,
  } from "./shader-gradient-vanilla"

  function cn(...parts: Array<string | false | null | undefined>) {
    return parts.filter(Boolean).join(" ")
  }

  interface Props extends Omit<ShaderGradientOptions, "onThemeChange"> {
    class?: string
  }

  let {
    class: className = "",
    colors,
    speed = DEFAULT_SPEED,
    blur = DEFAULT_BLUR,
    intensity = DEFAULT_INTENSITY,
    grain = DEFAULT_GRAIN,
    interactive = true,
    theme = "auto",
  }: Props = $props()

  let canvas: HTMLCanvasElement | undefined = $state()
  let isDark = $state(false)
  let instance: ShaderGradientInstance | null = null

  onMount(() => {
    const sync = () => {
      isDark = resolveDark(theme)
    }
    sync()
    const mo = new MutationObserver(sync)
    mo.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "data-theme"],
    })
    const mq = window.matchMedia("(prefers-color-scheme: dark)")
    mq.addEventListener("change", sync)

    if (!canvas) {
      return () => {
        mo.disconnect()
        mq.removeEventListener("change", sync)
      }
    }
    instance = createShaderGradient(canvas, {
      colors,
      speed,
      blur,
      intensity,
      grain,
      interactive,
      theme,
      onThemeChange: (dark) => {
        isDark = dark
      },
    })
    return () => {
      mo.disconnect()
      mq.removeEventListener("change", sync)
      instance?.destroy()
      instance = null
    }
  })

  $effect(() => {
    isDark = resolveDark(theme)
  })

  $effect(() => {
    instance?.setOptions({
      colors,
      speed,
      blur,
      intensity,
      grain,
      interactive,
      theme,
    })
  })

  const fallback = $derived(isDark ? DARK_FALLBACK : LIGHT_FALLBACK)
</script>

<div
  data-slot="shader-gradient"
  aria-hidden="true"
  class={cn("pointer-events-none absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]", className)}
  style="background-color: {fallback.backgroundColor}; background-image: {fallback.backgroundImage};"
>
  <!-- Firefox can hand an opaque WebGL canvas straight to the system
       compositor, which ignores rounded clips. The mask on the root keeps it
       in the page's own layer, so the parent's radius holds. -->
  <canvas bind:this={canvas} class="absolute inset-0 size-full rounded-[inherit]"></canvas>
</div>

// registry/shader-gradient/shader-gradient.tsx
"use client"

import { useEffect, useRef, useState } from "react"

import { cn } from "@/lib/utils"

import {
  createShaderGradient,
  DARK_FALLBACK,
  DEFAULT_BLUR,
  DEFAULT_GRAIN,
  DEFAULT_INTENSITY,
  DEFAULT_SPEED,
  LIGHT_FALLBACK,
  resolveDark,
  type ShaderGradientInstance,
  type ShaderGradientOptions,
} from "./shader-gradient-vanilla"

export {
  DARK_COLORS,
  DARK_FALLBACK,
  DEFAULT_BLUR,
  DEFAULT_GRAIN,
  DEFAULT_INTENSITY,
  DEFAULT_SPEED,
  LIGHT_COLORS,
  LIGHT_FALLBACK,
} from "./shader-gradient-vanilla"
export type {
  ShaderGradientInstance,
  ShaderGradientOptions,
  ShaderGradientTheme,
} from "./shader-gradient-vanilla"

export type ShaderGradientProps = Omit<
  ShaderGradientOptions,
  "onThemeChange"
> & {
  className?: string
}

/**
 * A grainy liquid gradient for heroes and empty states: the palette flows
 * through slow warped noise under a film grain. Theme-aware.
 */
export function ShaderGradient({
  className,
  colors,
  speed = DEFAULT_SPEED,
  blur = DEFAULT_BLUR,
  intensity = DEFAULT_INTENSITY,
  grain = DEFAULT_GRAIN,
  interactive = true,
  theme = "auto",
}: ShaderGradientProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const instanceRef = useRef<ShaderGradientInstance | null>(null)
  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    const sync = () => setIsDark(resolveDark(theme))
    sync()
    const mo = new MutationObserver(sync)
    mo.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "data-theme"],
    })
    const mq = window.matchMedia("(prefers-color-scheme: dark)")
    mq.addEventListener("change", sync)
    return () => {
      mo.disconnect()
      mq.removeEventListener("change", sync)
    }
  }, [theme])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    instanceRef.current = createShaderGradient(canvas, {
      colors,
      speed,
      blur,
      intensity,
      grain,
      interactive,
      theme,
      onThemeChange: setIsDark,
    })
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
    // Engine reads live options via setOptions; mount once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    instanceRef.current?.setOptions({
      colors,
      speed,
      blur,
      intensity,
      grain,
      interactive,
      theme,
      onThemeChange: setIsDark,
    })
  }, [colors, speed, blur, intensity, grain, interactive, theme])

  const fallback = isDark ? DARK_FALLBACK : LIGHT_FALLBACK

  return (
    <div
      data-slot="shader-gradient"
      aria-hidden
      className={cn(
        "pointer-events-none absolute inset-0 overflow-hidden rounded-[inherit] [mask-image:linear-gradient(#000,#000)]",
        className
      )}
      style={{
        backgroundColor: fallback.backgroundColor,
        backgroundImage: fallback.backgroundImage,
      }}
    >
      {/* Firefox can hand an opaque WebGL canvas straight to the system
          compositor, which ignores rounded clips. The mask on the root keeps
          it in the page's own layer, so the parent's radius holds. */}
      <canvas
        ref={canvasRef}
        className="absolute inset-0 size-full rounded-[inherit]"
      />
    </div>
  )
}
